vim plugins as submodules

diff --git a/bin/dotfiles_submodule b/bin/dotfiles_submodule
--- a/bin/dotfiles_submodule
+++ b/bin/dotfiles_submodule
@@ -1,13 +1,32 @@
-#!/bin/sh
+#!/bin/zsh
 
 
-if [[ $# -ne 2 ]]; then
-  echo "Usage: `basename $0` git-src destination"
-  exit 1
+if [[ $# -ne 2 ]] 
+then
+  echo -e "\e[1;31m Usage: `basename $0` git-src destination" ;
+  exit 1 ;
 fi
 
 SRC=$1
 DST=$2
 
+if [[ -d $DST ]]
+then
+  echo -e "\e[1;31m $DST already exists, exiting"
+  exit 2
+fi
+
+#DOTFILES='git --git-dir=$HOME/Src/dotfiles.git/ --work-tree=$HOME'
+
+echo "Cloning ${SRC} to ${DST}...\n"
 git clone "$SRC" "$DST"
-dotfiles submodule add "$SRC" "$DST"
+[[ $? -eq 0 ]] || (echo -e "\e[1;31m failed !" && exit 3)
+echo -e "\n\e[1;32mSucceded !\e[0m"
+cd $HOME
+echo "\nMaking ${DST} a submodule...\n"
+git --git-dir=$HOME/Src/dotfiles.git/ --work-tree=$HOME submodule add "$SRC" "$DST"
+[[ $? -eq 0 ]] || (echo -e "\n\e[1;31m failed !" && cd - && exit 3)
+echo -e "\n\e[1;32mSucceded !\e[0m"
+cd -
+
+exit 0
